#!/bin/bash

if [ $(id -u) != 0 ]; then echo "You must be root to install JustBOOT!"; exit 1;fi

mkdir -p /usr/share/justboot
cp -a data /usr/share/justboot
[ ! -d /etc/justboot ] && mkdir /etc/justboot 
cp -a etc/* /etc/justboot
cp justboot /usr/sbin
chmod +x /usr/sbin/justboot
echo "JustBOOT installed"

