#!/bin/bash

if [ $(whoami) != root ]; then echo "You must be root to uninstall JustBOOT!"; exit 1;fi

for i in i{4,5,6} x86_64; do
  if [[ -h /usr/share/justboot/${i} ]]; then
    echo "Removing ${i} build..."
    rm -rf $(readlink /usr/share/justboot/${i})
    rm -rf $(readlink /usr/share/justboot/excludes/${i})
  fi
done
rm -rf /usr/share/justboot /usr/sbin/justboot /etc/justboot

echo "JustBOOT uninstalled"

